### ISSUE TITLE
在添加语言文件下app.vue报错的问题以及在vscode文件夹中settings.json

### ISSUE THREAD

**Issue by master748** [w4ng3/web-course-docs#4]
问题1:在添加语言文件下app.vue报错的问题
问题2:.在vscode文件夹中settings.json添加老表，睁眼看世界啦文档中
```json
{
  "i18n-ally.localesPaths": ["packages/math-project-vue/locales"],
  "i18n-ally.sourceLanguage": "en",
  "i18n-ally.keystyle": "nested",
  "i18n-ally.sortKeys": true
}
```
不知道添加到哪里的问题
地址：https://github.com/master748/webmonorepo-main-02/tree/main/webmonorepo-main

**Comment by w4ng3** [comment]
参考我的仓库里的配置 https://github.com/w4ng3/web-monorepo/blob/main/.vscode/settings.json
可以直接下载我这个项目在你本地跑一下。
我看你是idea创建的项目，我这个是vscode的配置，在idea里应该不生效

**Comment by w4ng3** [comment]
第一个问题还是在main.js文件里，你在`const i18n = createI18n(...`后没有把插件注入到app实例里，需要 `app.use(i18n);`

问题解决了的话回复一下【已解决】

**Comment by master748** [comment]
第一个问题并没有解决 在app.vue中
![4d684526-0e4b-4c0f-b886-243e07369b83](https://github.com/user-attachments/assets/af29d60e-7621-4185-835b-8a92f0cb6a3c)
依然报错

**Comment by master748** [comment]
第一个问题并没有解决 在app.vue中依然报错
<img width="560" alt="屏幕截图 2024-09-29 191707" src="https://github.com/user-attachments/assets/e8e38d2a-8a02-42b4-90f9-6cde5b796d0c">

**Comment by w4ng3** [comment]
> 第一个问题并没有解决 在app.vue中依然报错 <img alt="屏幕截图 2024-09-29 191707" width="560" src="https://private-user-images.githubusercontent.com/180358527/371849330-e8e38d2a-8a02-42b4-90f9-6cde5b796d0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MDk0NzYsIm5iZiI6MTcyNzYwOTE3NiwicGF0aCI6Ii8xODAzNTg1MjcvMzcxODQ5MzMwLWU4ZTM4ZDJhLThhMDItNDJiNC05MGY5LTZjZGU1Yjc5NmQwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQxMTI2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNWJkOTZkMWRmMDFmOGZlOTRhYTU0NTNkOTkxMjg0ODI1NDc2ZDFhNWY2NTdhNGRmZmUwNDZhNDZmM2U3NmU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._Wj_4BjzOV6Aur9GyNfzR2ng64ABK-ZIE2sQzMg9o5I">

仔细对照文档里的变量名称，我后面都改了名了，whatsyouname这个计算属性值你定义了么？，你还是先跑一下我的代码吧。
而且不要每次都创建新的仓库，git仓库是可以修改代码、添加记录、推送仓库的。
去了解下代码推送的基本命令
```bash
git add .
git commit -m "提交描述....."
git push origin main
```
多问问同学这么管理代码

**Comment by w4ng3** [comment]
不要把不相关的代码都放在一起，特别是放在app.vue里，之前都带着写了一个知乎热榜组件了，你就依葫芦画瓢自己创建一个组件，专门写多语言相关的代码
