### ISSUE TITLE
使用Vue i18n插件时的问题

### ISSUE THREAD

**Issue by alwayXXX** [w4ng3/web-course-docs#5]
Github:https://github.com/alwayXXX/web-course-project/
### $t 函数没有正确地返回对应的翻译文本
![image](https://github.com/user-attachments/assets/79457c11-0aca-4091-babb-cc22495d1ff3)

**Comment by w4ng3** [comment]
看了你的仓库结构，似乎是翻译文件夹路径没对应导致的，vite.config.ts里的配置的VueI18n翻译文件路径指向项目根路径下的locales文件夹，而你的翻译文件放在 src/locales里；
可以运行我的仓库跑一跑看看 https://github.com/w4ng3/web-monorepo

**Comment by w4ng3** [comment]
应该还有一个错误，`vue-i18n`要安装 `10`开头的版本，在 https://vue-i18n.intlify.dev/guide/installation.html 官方文档里说明了，vue3要安装的版本，我目前的版本是 ` "vue-i18n": "^10.0.3",`

**Comment by alwayXXX** [comment]
![image](https://github.com/user-attachments/assets/2010ff6c-28fa-4c43-9ac0-d82ce57ecf4a)
错误已得到纠正
